### PR TITLE
Integrate with Travis and Codecov

### LINKED ISSUE #107: Use Canoconical Unittest Naming Convention
Unittest expects filenames to be of the form...
`test_xyz.py`
`test_abc.py`
etc

The current naming convention makes it more difficult to run unittest with discovery.

### PR DESCRIPTION
**Pull request by ThomasThelen**
This PR adds a .travis.yml file so that when a new commit is pushed, a build gets kicked off and code coverage metrics are updated (looks like you're around 90% coverage :)). Adding support for other versions of Python should be obvious enough. I also renamed the test files so unittetst can find them.

This also allows you to add coverage and travis badges to the readme.

Fixes #107 and #108

### CODE REVIEW

**Comment by theJollySin** [comment]
I like the idea.

So, we add the Travis YML file.  Neat.  And then what?  Will GitHub automatically start running CI build items?  Or do I have to set up a personal server with with to run these CI steps?

I have CI integration at work, of course.  But Travis is not part of our tool chain, and I'm certainly used to having to set up my own CI systems and environments.  So, if GitHub *will* handle all of this for me, great!   But I figure I should ask.

Thanks!

**Comment by ThomasThelen** [comment]
The two requisites are (as much as I hate creating new accounts-you can sign in with GitHub on these)
1. travis account
1. codecov account

Travis will automatically kick off a build when the `master` branch is updated; the last line in the yaml file is telling codecov to update its record.

The best parts are, of course, the badges. See [this](https://github.com/ThomasThelen/SDTLpy), for example. Travis and Codecov should give you the markdown snippets to embed them in your readme, but it should look like

```
[![Build Status](https://travis-ci.org/theJollySin/mazelib.svg?branch=master)](https://travis-ci.org/ThomasThelen/SDTLpy)
[![codecov](https://codecov.io/gh/theJollySin/mazelib/branch/master/graph/badge.svg)](https://codecov.io/gh/theJollySin/mazelib)
[![Python 3.8](https://img.shields.io/badge/python-3.8-blue.svg)]()
```

**Comment by theJollySin** [comment]
@ThomasThelen  Okay, so I have to create an account.  I don't have one yet, so I'll have to do that.

Easy and free, I assume?

Also, should I make the account before merging the PR?

Thanks for all the help!

**Comment by ThomasThelen** [comment]
Go ahead and make the accounts before you merge the PR (it's free). I think you might need to add the repository to each service _before_ merging too. 
Both are largely used services and are pretty easy to set up (for basic things).

**Comment by theJollySin** [comment]
Ah, okay.  So the codecoverage did not actually work, it returned an error.  I guess I will have to look at that.

But the build is passing in Travis, which is nice.

**Pull request merged**
